---
- hosts: ubuntuos
  become: yes
  tasks:
  - name: installing apache server
    apt:
      name: apache2
      state: present
    notify: startwebserver

  - name: to copy the file into nodes
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startwebserver

  handlers: 
  - name: startwebserver
    service:
      name: apache2
      state: restarted    

