---
- hosts: all
  become: yes
  tasks:
  - name: installing apache web server
    apt:
      name: apache2
      state: present
  - name: start the apache2 server
    service:
      name: apache2
      state: started   